### ISSUE TITLE
Why is this repo necessary?

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/optimade-website-apex-redirect#1]
Why can't this be sorted by configuring the GitHub pages site? See [here](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) for configuring apex domain.

**Comment by rartino** [comment]
See the discussion in Materials-Consortia/materials-consortia.github.io#8, and in particular that we have the same issues people are reporting here: isaacs/github#1675

**Comment by CasperWA** [comment]
Right, thanks for the references! Closing this.
